Added explicit raw values to ChordType
AudioKit/Tonic pull request #48
Opened 2024-12-18 21:56 UTC by Matt54

By adding these raw values, we are free to continue to adjust the naming / spelling / fix any typos without causing any breaking changes. We just can't change the raw values.

Alternatively, if we don't care what the raw values are (nothing relies on them) - we could just pin each ChordType to an Int instead

2024-12-18 22:00 UTC, aure commented
I like this better than tying to an Int.

2024-12-18 22:01 UTC, aure approved these changes

2025-02-12 21:40 UTC, SebastianBoldt requested changes
Small but effective addition that enhances the robustness of the Framework 👏 

I would like to discuss the broader concept of making Chords Codable and 
maybe we can tackle this already in this PR 🤔 

Chords include:
* `root`
* `type`
* `inversion`

The **root** is a `NoteClass`, comprising of `letter` -> C, D, E, F, G, A, B
and `accidental` -> flat, sharp, double flat, and double sharp -> with appropriate raw values already in place.

The type `ChordType` is represented by a basic enum -> covered in your PR,
and `inversion` is simply an Integer so we are also good here I would say 👍 

Should we consider establishing explicit raw values for the `Letter` Type also already in this PR? This way, if someone opts to convert them to lowercase in the future, it won't result in any issues when trying to decode previously persisted chords.

Or should we just keep the current raw values that are inferred by the compiler (C, D, E etc - uppercased)?

Wdyt?

2025-02-13 00:26 UTC, aure requested changes
In the end I don't like this change. I don't think it's a big enough win deal with all this duplication.

2025-02-13 00:27 UTC, aure commented
> Small but effective addition that enhances the robustness of the Framework 👏
> 
> I would like to discuss the broader concept of making Chords Codable and maybe we can tackle this already in this PR 🤔
> 
> Chords include:
> 
> * `root`
> * `type`
> * `inversion`
> 
> The **root** is a `NoteClass`, comprising of `letter` -> C, D, E, F, G, A, B and `accidental` -> flat, sharp, double flat, and double sharp -> with appropriate raw values already in place.
> 
> The type `ChordType` is represented by a basic enum -> covered in your PR, and `inversion` is simply an Integer so we are also good here I would say 👍
> 
> Should we consider establishing explicit raw values for the `Letter` Type also already in this PR? This way, if someone opts to convert them to lowercase in the future, it won't result in any issues when trying to decode previously persisted chords.
> 
> Or should we just keep the current raw values that are inferred by the compiler (C, D, E etc - uppercased)?
> 
> Wdyt?

The letter type idea is fine we could do it in another PR though

2025-02-13 00:27 UTC, closed without merging

2025-02-13 12:47 UTC, Matt54 commented
At the end of the day, I see 3 options:
- explicit integer raw values
- explicit string raw values
- keep implicit string raw values (but plan to never change the existing cases)

explicit Integer raw values:
downside = saved files lose readability

explicit String raw values
downside = we are stuck with the spelling of the raw values

implicit String raw values
downside = we cannot change existing cases (spelling/typos/etc.) 

IMO, the least bad option is explicit integer and the worst option is implicit string. 

I know it's an eye sore to add the explicit raw values, but it feels like a safer approach to managing a core / model package.

2025-02-13 12:50 UTC, SebastianBoldt commented
I think I'll avoid the raw values entirely for persistence purposes and instead 
incorporate an additional layer to store those values independently of the implementation details. 

It might add some overhead but in that case I can be sure that the package implementation won't break my persistence layer.

2025-02-13 12:54 UTC, Matt54 commented
> I think I'll avoid the raw values entirely for persistence purposes and instead incorporate an additional layer to store those values independently of the implementation details.
> 
> It might add some overhead but in that case I can be sure that the package implementation won't break my persistence layer.

Good point - that's probably going to be my strategy as well. Otherwise it's a scary custom decoding path to walk 😅